[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.17'
optimizer_runs = 0xffffffff
viaIR = true

[fuzz]
# runs = 250000

[invariant]
runs = 400
depth = 40
fail_on_revert = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
