[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.17'
optimizer_runs = 0xffffffff
viaIR = true

[fuzz]
# runs = 250000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
